spring.application.name=SS12_B3


#Config datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_ss12_b3?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=06072006